# Generated by Django 2.0.7 on 2020-04-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'managed': False, 'verbose_name_plural': 'measurements'},
        ),
        migrations.AlterModelTable(
            name='measurements',
            table='measurements',
        ),
    ]
