# Generated by Django 2.0.7 on 2020-04-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200428_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'managed': False, 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelTable(
            name='measurements',
            table='Measurements',
        ),
    ]
